# Logistic regression

In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the librairies

In [76]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

## Importing the dataset

In [77]:
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

## Splitting the dataset into training and test set

In [78]:
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.25, random_state=1)

In [79]:
print(X_train)

[[    20  49000]
 [    46  88000]
 [    31  34000]
 [    47  30000]
 [    35  50000]
 [    39  96000]
 [    33 113000]
 [    49  86000]
 [    45  79000]
 [    44  39000]
 [    41  59000]
 [    42  53000]
 [    35  73000]
 [    41  72000]
 [    27  96000]
 [    30 116000]
 [    41  52000]
 [    41  52000]
 [    20  82000]
 [    46  41000]
 [    27  31000]
 [    35  71000]
 [    49  28000]
 [    35  91000]
 [    37  75000]
 [    32 117000]
 [    36  75000]
 [    20  86000]
 [    38  50000]
 [    49  36000]
 [    40  65000]
 [    37  77000]
 [    60  46000]
 [    48 138000]
 [    40  71000]
 [    36  63000]
 [    26  81000]
 [    33  31000]
 [    41  51000]
 [    46  74000]
 [    18  82000]
 [    37  33000]
 [    35  53000]
 [    28  59000]
 [    37  71000]
 [    18  44000]
 [    38  61000]
 [    35  65000]
 [    31  66000]
 [    47  25000]
 [    42 104000]
 [    19  19000]
 [    21  72000]
 [    28  32000]
 [    52 150000]
 [    53 104000]
 [    25  80000]
 [    26  72000]
 [    26  1500

In [80]:
print(X_test)

[[    36  33000]
 [    39  61000]
 [    36 118000]
 [    39 122000]
 [    26 118000]
 [    38  65000]
 [    20  36000]
 [    49  89000]
 [    31  18000]
 [    48 141000]
 [    34  72000]
 [    39  73000]
 [    35  72000]
 [    48 131000]
 [    53  82000]
 [    56 133000]
 [    60  83000]
 [    27  58000]
 [    28  87000]
 [    60 102000]
 [    40  75000]
 [    50  88000]
 [    44 139000]
 [    47  43000]
 [    45  26000]
 [    26  15000]
 [    58  47000]
 [    49  74000]
 [    53  34000]
 [    52 114000]
 [    39  42000]
 [    19  76000]
 [    18  86000]
 [    57  74000]
 [    27  84000]
 [    30  80000]
 [    22  18000]
 [    32  86000]
 [    50  20000]
 [    19  25000]
 [    47 144000]
 [    58 101000]
 [    34 115000]
 [    23  66000]
 [    56  60000]
 [    31 118000]
 [    48  35000]
 [    47 113000]
 [    39  79000]
 [    52  38000]
 [    24  58000]
 [    37  53000]
 [    42  80000]
 [    46  28000]
 [    42  73000]
 [    37  62000]
 [    60  42000]
 [    36  52000]
 [    58  9500

## Feature scaling

In [81]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_y.fit_transform(X_test)

In [82]:
print(X_train)

[[-1.68062015e+00 -5.92416706e-01]
 [ 8.69241193e-01  5.63566526e-01]
 [-6.01832657e-01 -1.03702564e+00]
 [ 9.67312783e-01 -1.15558802e+00]
 [-2.09546297e-01 -5.62776110e-01]
 [ 1.82740063e-01  8.00691292e-01]
 [-4.05689477e-01  1.30458142e+00]
 [ 1.16345596e+00  5.04285335e-01]
 [ 7.71169603e-01  2.96801165e-01]
 [ 6.73098013e-01 -8.88822663e-01]
 [ 3.78883243e-01 -2.96010749e-01]
 [ 4.76954833e-01 -4.73854323e-01]
 [-2.09546297e-01  1.18957591e-01]
 [ 3.78883243e-01  8.93169951e-02]
 [-9.94119017e-01  8.00691292e-01]
 [-6.99904247e-01  1.39350321e+00]
 [ 3.78883243e-01 -5.03494919e-01]
 [ 3.78883243e-01 -5.03494919e-01]
 [-1.68062015e+00  3.85722952e-01]
 [ 8.69241193e-01 -8.29541472e-01]
 [-9.94119017e-01 -1.12594743e+00]
 [-2.09546297e-01  5.96763994e-02]
 [ 1.16345596e+00 -1.21486922e+00]
 [-2.09546297e-01  6.52488313e-01]
 [-1.34031173e-02  1.78238782e-01]
 [-5.03761067e-01  1.42314380e+00]
 [-1.11474707e-01  1.78238782e-01]
 [-1.68062015e+00  5.04285335e-01]
 [ 8.46684727e-02 -5

In [83]:
print(X_test)

[[-2.89053269e-01 -1.11810479e+00]
 [-1.89100270e-02 -3.15568669e-01]
 [-2.89053269e-01  1.31816558e+00]
 [-1.89100270e-02  1.43281360e+00]
 [-1.18953074e+00  1.31816558e+00]
 [-1.08957774e-01 -2.00920651e-01]
 [-1.72981723e+00 -1.03211878e+00]
 [ 8.81567447e-01  4.86967455e-01]
 [-7.39292006e-01 -1.54803486e+00]
 [ 7.91519700e-01  1.97739168e+00]
 [-4.69148764e-01 -2.86620044e-04]
 [-1.89100270e-02  2.83753844e-02]
 [-3.79101017e-01 -2.86620044e-04]
 [ 7.91519700e-01  1.69077164e+00]
 [ 1.24175844e+00  2.86333424e-01]
 [ 1.51190168e+00  1.74809565e+00]
 [ 1.87209267e+00  3.14995428e-01]
 [-1.09948300e+00 -4.01554682e-01]
 [-1.00943525e+00  4.29643446e-01]
 [ 1.87209267e+00  8.59573512e-01]
 [ 7.11377205e-02  8.56993932e-02]
 [ 9.71615195e-01  4.58305450e-01]
 [ 4.31328710e-01  1.92006768e+00]
 [ 7.01471952e-01 -8.31484748e-01]
 [ 5.21376458e-01 -1.31873882e+00]
 [-1.18953074e+00 -1.63402087e+00]
 [ 1.69199717e+00 -7.16836730e-01]
 [ 8.81567447e-01  5.70373888e-02]
 [ 1.24175844e+00 -1

## Training the logistic regression model on the treaining set

In [84]:
from sklearn.linear_model import LogisticRegression
LGR = LogisticRegression(random_state=0)
LGR.fit(X_train, Y_train)

LogisticRegression(random_state=0)

## Predicting a new result

In [89]:
print(LGR.predict(sc_X.transform([[30,87000]])))

[0]


## Predicting the test set results

## Making the confusion matrix

## Visualizing the training set results

## Visualizing the test set results