 # ANN
 


## Importing librairies

In [2]:
!pip install tensorflow

  Using cached tensorflow-2.7.0-cp38-cp38-win_amd64.whl (430.8 MB)
  Using cached flatbuffers-2.0-py2.py3-none-any.whl (26 kB)
  Using cached absl_py-0.15.0-py3-none-any.whl (132 kB)
  Using cached termcolor-1.1.0-py3-none-any.whl
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached libclang-12.0.0-py2.py3-none-win_amd64.whl (13.1 MB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached tensorboard-2.7.0-py3-none-any.whl (5.8 MB)
  Using cached tensorflow_io_gcs_filesystem-0.21.0-cp38-cp38-win_amd64.whl (1.5 MB)
  Using cached keras-2.7.0-py2.py3-none-any.whl (1.3 MB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached tensorflow_estimator-2.7.0-py2.py3-none-any.whl (463 kB)
  Using cached protobuf-3.19.1-cp38-cp38-win_amd64.whl (895 kB)
  Using cached grpcio-1.41.1-cp38-cp38-win_amd64.whl (3.2 MB)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
  Us

In [3]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

In [4]:
tf.__version__

'2.7.0'

## Importing dataset

In [9]:
dataset = pd.read_csv(r"C:\Users\Aymen\Documents\GitHub\MyOwnDSMLLearning\datasets\Churn_Modelling.csv")
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [12]:
dataset.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [11]:
list(dataset.columns)

['RowNumber',
 'CustomerId',
 'Surname',
 'CreditScore',
 'Geography',
 'Gender',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary',
 'Exited']

In [13]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


## Encoding categorical data

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [19]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


## One hot encoding

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [21]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

## Splitting the dataset into train and test set

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature scaling

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Initializing the ANN

In [26]:
ann = tf.keras.models.Sequential()

## Adding the input layer and the first hidden layer

In [28]:
ann.add(tf.keras.layers.Dense(units= 6, activation = 'relu'))

## Adding the second hidden layer

In [29]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

## Adding the output layer

In [30]:
ann.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid'))

## Compiling the ANN

In [31]:
ann.compile(optimizer= 'adam' ,loss= 'binary_crossentropy' , metrics= ['accuracy'])

## Training the ANN on the training set

In [32]:
ann.fit(X_train, y_train,batch_size= 32, epochs= 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5186 - accuracy: 0.7919
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4461 - accuracy: 0.8044
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4308 - accuracy: 0.8138
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4214 - accuracy: 0.8190
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4146 - accuracy: 0.8246
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4083 - accuracy: 0.8264
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4014 - accuracy: 0.8300
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3927 - accuracy: 0.8359
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3831 - accuracy: 0.8401
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3725 - accura

250/250 [==============================] - 0s 1ms/step - loss: 0.3382 - accuracy: 0.8627
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3381 - accuracy: 0.8635
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3376 - accuracy: 0.8635
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3373 - accuracy: 0.8636
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3376 - accuracy: 0.8626
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3374 - accuracy: 0.8619
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3375 - accuracy: 0.8625
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3373 - accuracy: 0.8625
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3375 - accuracy: 0.8639
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3373 - accuracy: 

## Predicting the result of of a single observation

In [37]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,5000]]))> 0.5)

[[False]]


## Predicting the result of the test set 

In [45]:
y_pred = (ann.predict(X_test) >0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Matrix of confusion

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1503   92]
 [ 184  221]]


0.862